name: Terraform-iac-pipeline
on: push
jobs:
 terraform-job:
  runs-on: ubuntu-22.04
  steps:
  
      - name: checkout the code
        uses: actions/checkout@v5
        with:
              fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: us-west-2

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Check TF version
        run: terraform -version
        
      - name: TF init
        run: terraform init
        
      - name: TF format
        run: terraform fmt

      - name: TF validate
        run: terraform validate

      - uses: terraform-linters/setup-tflint@v6
        name: Setup TFLint
        with:
             tflint_version: v0.52.0
             
      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
            GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact
        
      - name: TF plan
        run: terraform plan

      - name: TF apply
        run: terraform apply -auto-approve
